server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${email.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  mustache:
    expose-session-attributes: true
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # 조심하자!! 젭알 ㅠ

file:
  path: /home/ubuntu/upload/

logging:
  level:
    '[site.metacoding.blogv3]': INFO