server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssarmango
    password: apxkzheld8241!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  security:
    user:
      name: test
      password: 1234
  mustache:
    expose-session-attributes: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

file:
  path: ./upload/

logging:
  level:
    '[site.metacoding.blogv3]': DEBUG
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기